# Please note that the plot generated by this script shows the same data as the figure in the paper. However, in the paper the layout was adapted to fit the page
# and to make the labels readable.
# These adjustments were done manually by using the interactive GUI of matplotlib.
# If make use of plt.show(), the plot will be displayed in the interactive GUI of matplotlib and you can perform layout adjustments there
# However, this approach is unsuitable for the pipeline and for the Docker container.

import os
import json
import csv
import requests
import logging
import numpy as np
import umap.umap_ as umap
import matplotlib.pyplot as plt
from typing import Optional, List, Tuple
from matplotlib import rcParams
from matplotlib.patches import Patch

# ---------------- Config / paths ----------------
# Minimal changes: make paths/env configurable for the container
PLOTS_DIR = os.getenv("PLOTS_DIR", "/app/exports/plots")
TOP_EXPORT_DIR = os.getenv("TOP100_EXPORT_DIR", "/app/exports/top_100_drugs_for_umap_plot")
DATASETS_DIR = os.getenv("DATASETS_DIR", "/app/datasets")


EMBED_URL = os.getenv("OLLAMA_URL", "http://ollama:11434/api/embed")
EMBED_MODEL = os.getenv("EMBED_MODEL", "llama3:8b")

# Input files (Top-30 lists & literature JSON)
FILE_ZERO_SHOT_30 = os.path.join(TOP_EXPORT_DIR, "zero_shot_top_30.csv")
FILE_STATIC_30 = os.path.join(TOP_EXPORT_DIR, "ontological_prompt_top_30.csv")
FILE_LITERATURE = os.path.join(DATASETS_DIR, "cummings_eta_al_AD_DR_candidates.json")

# Output plot
OUTPUT_PLOT = os.path.join(PLOTS_DIR, "approaches_umap_annotated_text_jittered.png")

# ---------------- Logging ----------------
logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    level=logging.DEBUG  # leave as DEBUG for detailed run logs
)
logger = logging.getLogger(__name__)

# ---------------- Matplotlib style ----------------
plt.style.use('seaborn-v0_8-whitegrid')
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Arial', 'Helvetica', 'DejaVu Sans']

# Color-blind friendly palette
APPROACH_STYLES = {
    "zero_shot": {
        "color": "#0072B2",  # Blue
        "name": "Zero-Shot Prompting"
    },
    "static_prompt": {
        "color": "#D55E00",  # Orange
        "name": "Ontology-Based Prompting"
    },
    "literature": {
        "color": "#009E73",  # Green
        "name": "Literature Comparison"
    }
}

# ---------------- Helpers ----------------
def _load_drug_list(path: str) -> list:
    """
    Load a list of drug names. Supports:
      - CSV (expects 'name' column)
      - JSON (list of strings, or dict keys as names)
    """
    if not os.path.exists(path):
        logger.error("Input file not found: %s", path)
        return []

    _, ext = os.path.splitext(path.lower())
    try:
        if ext == ".csv":
            names = []
            with open(path, "r", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                if "name" not in reader.fieldnames:
                    logger.error("CSV %s lacks a 'name' column.", path)
                    return []
                for row in reader:
                    nm = row.get("name")
                    if nm:
                        names.append(nm)
            logger.info("Loaded %d drug names from CSV: %s", len(names), path)
            return names

        # JSON
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            logger.info("Loaded %d drug names from JSON list: %s", len(data), path)
            return data
        elif isinstance(data, dict):
            keys = list(data.keys())
            logger.info("Loaded %d drug names from JSON dict keys: %s", len(keys), path)
            return keys
        else:
            logger.error("Unsupported JSON structure in %s", path)
            return []
    except Exception as e:
        logger.error("Failed to load %s: %s", path, e)
        return []

def get_embedding_for_drug(drug: str, model: str) -> Optional[np.ndarray]:
    payload = {
        "model": model,
        "input": drug
    }
    logger.debug("Requesting embedding for '%s' using model '%s'", drug, model)
    try:
        resp = requests.post(EMBED_URL, json=payload)
        resp.raise_for_status()
        data = resp.json()
        emb = data.get("embeddings", [[]])[0]
        if not emb:
            logger.error("Empty embedding for '%s'", drug)
            return None
        logger.info("Embedding for '%s' received (len=%d)", drug, len(emb))
        return np.array(emb, dtype=float)
    except requests.RequestException as err:
        logger.error("Embedding request failed for '%s': %s", drug, err)
        return None

def embed_list(drug_list: list, model: str) -> dict:
    out = {}
    for d in drug_list:
        emb = get_embedding_for_drug(d, model)
        if emb is not None:
            out[d] = emb
        else:
            logger.warning("Skipping '%s' due to failed embedding.", d)
    return out

def run_through_all_approaches(approach_files: dict, model: str) -> dict:
    all_embs = {}
    for approach, file_path in approach_files.items():
        drugs = _load_drug_list(file_path)
        if not drugs:
            logger.warning("No drugs loaded for approach '%s' from %s", approach, file_path)
            all_embs[approach] = {}
            continue
        embs = embed_list(drugs, model)
        all_embs[approach] = embs
    return all_embs

def combine_embeddings_for_visualization(all_embeddings: dict) -> tuple:
    combined_embeddings = []
    combined_labels = []
    combined_drug_names = []

    for approach, emb_dict in all_embeddings.items():
        for drug, emb in emb_dict.items():
            combined_embeddings.append(emb)
            combined_labels.append(approach)
            combined_drug_names.append(drug)

    if combined_embeddings:
        combined_embeddings = np.vstack(combined_embeddings)
        logger.info("Combined %d embeddings for visualization.", combined_embeddings.shape[0])
    else:
        combined_embeddings = np.zeros((0, 2), dtype=float)

    return combined_embeddings, combined_labels, combined_drug_names

def main():
    os.makedirs(PLOTS_DIR, exist_ok=True)

    # Files for top-30:
    approach_files = {
        "zero_shot": FILE_ZERO_SHOT_30,
        "static_prompt": FILE_STATIC_30,
        "literature": FILE_LITERATURE,
    }

    logger.info("Using embed endpoint: %s | model=%s", EMBED_URL, EMBED_MODEL)
    logger.info("Top-30 inputs: %s", approach_files)

    all_embeddings = run_through_all_approaches(approach_files, EMBED_MODEL)
    combined_embeddings, labels, drug_names = combine_embeddings_for_visualization(all_embeddings)

    if combined_embeddings.shape[0] == 0:
        logger.critical("No embeddings available to plot. Check inputs and embedding service.")
        return

    # UMAP to 2D
    umap_model = umap.UMAP(n_components=2, random_state=42)
    logger.info("Fitting UMAP on %d embeddings.", combined_embeddings.shape[0])
    embedding_2d = umap_model.fit_transform(combined_embeddings)
    logger.info("UMAP complete. Shape: %s", embedding_2d.shape)

    # Scale up to spread points
    scale_factor = 200
    embedding_2d = embedding_2d * scale_factor

    # Figure
    plt.figure(figsize=(16, 12))
    ax = plt.gca()
    ax.set_facecolor('#F8F9F9')
    plt.gcf().set_facecolor('#F8F9F9')

    # Plot invisible points (anchors for text)
    plt.scatter(embedding_2d[:, 0], embedding_2d[:, 1], alpha=0)

    # Jitter
    jitter_factor_x = (np.max(embedding_2d[:, 0]) - np.min(embedding_2d[:, 0])) * 0.07
    jitter_factor_y = (np.max(embedding_2d[:, 1]) - np.min(embedding_2d[:, 1])) * 0.05

    def truncate_label(label: str, max_length: int = 20) -> str:
        return label if len(label) <= max_length else label[:max_length-3] + "..."

    # Annotate each point with a colored-bordered text box per approach
    for i, drug in enumerate(drug_names):
        approach = labels[i]
        style = APPROACH_STYLES[approach]
        x, y = embedding_2d[i, 0], embedding_2d[i, 1]
        x_j = x + np.random.uniform(-jitter_factor_x, jitter_factor_x)
        y_j = y + np.random.uniform(-jitter_factor_y, jitter_factor_y)

        plt.text(
            x_j, y_j, truncate_label(drug),
            color='black',
            fontsize=28,
            fontweight='medium',
            alpha=0.9,
            bbox=dict(
                facecolor='white',
                edgecolor=style["color"],
                alpha=0.9,
                pad=3,
                boxstyle='round,pad=0.4'
            )
        )

    plt.xlabel("UMAP Dimension 1", labelpad=15, fontsize=30, color='#2C3E50')
    plt.ylabel("UMAP Dimension 2", labelpad=15, fontsize=30, color='#2C3E50')
    ax.tick_params(axis='both', which='major', labelsize=28)
    plt.grid(True, linestyle='--', alpha=0.3, color='#95A5A6')

    legend_handles = []
    for approach, style in APPROACH_STYLES.items():
        legend_handles.append(Patch(facecolor='white', edgecolor=style["color"], label=style["name"], alpha=0.9))
    plt.legend(handles=legend_handles, loc="best", fontsize=30, frameon=True, facecolor='white', edgecolor='none', framealpha=0.9)

    plt.subplots_adjust(left=0.1, right=0.9, top=0.9, bottom=0.1)

    plt.savefig(OUTPUT_PLOT, dpi=600, bbox_inches='tight', facecolor='#F8F9F9', edgecolor='none')
    logger.info("Annotated, jittered UMAP plot saved to %s", OUTPUT_PLOT)

if __name__ == "__main__":
    main()