# Please note that the plot generated by this script shows the same data as the figure in the paper. However, in the paper the layout was adapted to fit the page
# and to make the labels readable.
# These adjustments were done manually by using the interactive GUI of matplotlib.
# If make use of plt.show(), the plot will be displayed in the interactive GUI of matplotlib and you can perform layout adjustments there
# However, this approach is unsuitable for the pipeline and for the Docker container.
import os
import json
import requests
import logging
import numpy as np
import umap.umap_ as umap
import matplotlib.pyplot as plt
from typing import Optional, List, Tuple
from matplotlib import rcParams
from matplotlib.patches import Patch
from matplotlib.text import Text
from matplotlib.transforms import Bbox

# ---------------- Paths / Env (minimal container tweaks) ----------------
PLOTS_DIR = os.getenv("PLOTS_DIR", "/app/exports/plots")
DATASETS_DIR = os.getenv("DATASETS_DIR", "/app/datasets")
VALIDATION_JSON = os.path.join(DATASETS_DIR, "validation_drug_list_for_visualization.json")


EMBED_URL = os.getenv("OLLAMA_URL", "http://ollama:11434/api/embed")
EMBED_MODEL = os.getenv("EMBED_MODEL", "llama3:8b")

# ---------------- Logging ----------------
logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    level=logging.DEBUG
)
logger = logging.getLogger(__name__)

# ---------------- Matplotlib style ----------------
plt.style.use('seaborn-v0_8-whitegrid')
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Arial', 'Helvetica', 'DejaVu Sans']

# Color scheme for validation drugs
VALIDATION_STYLE = {
    "color": "#0072B2",  # Blue
    "name": "Validation Drugs"
}

def get_embedding_for_drug(drug: str, model: str) -> Optional[np.ndarray]:
    """
    Get the embedding of a drug name by calling the Ollama embedding API.
    """
    payload = {"model": model, "input": drug}
    logger.debug("Requesting embedding for '%s' using model '%s'", drug, model)
    try:
        resp = requests.post(EMBED_URL, json=payload)
        resp.raise_for_status()
        data = resp.json()
        emb = data.get("embeddings", [[]])[0]
        if not emb:
            logger.error("Empty embedding for '%s'", drug)
            return None
        logger.info("Embedding for '%s' received (len=%d)", drug, len(emb))
        return np.array(emb, dtype=float)
    except requests.RequestException as err:
        logger.error("Error fetching embedding for '%s': %s", drug, err)
        return None

def embed_drugs(drug_list: list, model: str) -> dict:
    """
    Get embeddings for all drugs in the provided list.
    """
    embeddings = {}
    for drug in drug_list:
        emb = get_embedding_for_drug(drug, model)
        if emb is not None:
            embeddings[drug] = emb
        else:
            logger.warning("Skipping '%s' due to failed embedding.", drug)
    return embeddings

def get_text_bbox(text: Text) -> Bbox:
    """Get the bounding box of a text object in display coordinates."""
    renderer = text.figure.canvas.get_renderer()
    return text.get_window_extent(renderer)

def check_overlap(b1: Bbox, b2: Bbox, padding: float = 5) -> bool:
    """Check if two bounding boxes overlap with padding."""
    return (b1.x0 - padding < b2.x1 + padding and
            b1.x1 + padding > b2.x0 - padding and
            b1.y0 - padding < b2.y1 + padding and
            b1.y1 + padding > b2.y0 - padding)

def find_optimal_position(text: Text, existing_texts: List[Text],
                          x: float, y: float, ax: plt.Axes,
                          max_attempts: int = 8) -> Tuple[float, float]:
    """Find an optimal position for a text label that minimizes overlap."""
    angles = np.linspace(0, 2*np.pi, max_attempts, endpoint=False)
    distances = [15, 30, 45]
    best_pos = (x, y)
    min_overlaps = float('inf')

    for dist in distances:
        for ang in angles:
            dx = dist * np.cos(ang)
            dy = dist * np.sin(ang)
            nx, ny = x + dx, y + dy
            text.set_position((nx, ny))
            nb = get_text_bbox(text)
            overlaps = sum(1 for ex in existing_texts if check_overlap(nb, get_text_bbox(ex)))
            if overlaps < min_overlaps:
                min_overlaps = overlaps
                best_pos = (nx, ny)
            if overlaps == 0:
                return best_pos
    return best_pos

def main():
    # Ensure output dir exists
    os.makedirs(PLOTS_DIR, exist_ok=True)

    # Load validation drug list
    if not os.path.exists(VALIDATION_JSON):
        logger.critical("Validation list not found at %s", VALIDATION_JSON)
        return

    with open(VALIDATION_JSON, "r", encoding="utf-8") as f:
        drug_list = json.load(f)

    if not isinstance(drug_list, list) or not drug_list:
        logger.critical("Validation file is empty or not a list: %s", VALIDATION_JSON)
        return

    logger.info("Using embed endpoint: %s | model=%s", EMBED_URL, EMBED_MODEL)
    embeddings = embed_drugs(drug_list, EMBED_MODEL)

    if not embeddings:
        logger.critical("No embeddings produced; cannot plot.")
        return

    drug_names = list(embeddings.keys())
    embedding_vectors = np.vstack(list(embeddings.values()))

    # UMAP
    umap_model = umap.UMAP(n_components=2, random_state=42)
    logger.info("Fitting UMAP on %d embeddings.", embedding_vectors.shape[0])
    emb2d = umap_model.fit_transform(embedding_vectors)
    logger.info("UMAP reduction complete. Shape: %s", emb2d.shape)

    # Scale up for spacing
    scale_factor = 200
    emb2d = emb2d * scale_factor

    # Figure
    plt.figure(figsize=(32, 12))
    ax = plt.gca()
    ax.set_facecolor('#F8F9F9')
    plt.gcf().set_facecolor('#F8F9F9')

    # Invisible scatter to anchor text
    plt.scatter(emb2d[:, 0], emb2d[:, 1], alpha=0)

    # Jitter for readability
    jx = (np.max(emb2d[:, 0]) - np.min(emb2d[:, 0])) * 0.05
    jy = (np.max(emb2d[:, 1]) - np.min(emb2d[:, 1])) * 0.05

    def trunc(label: str, n: int = 20) -> str:
        return label if len(label) <= n else label[:n-3] + "..."

    existing_texts: List[Text] = []
    for i, drug in enumerate(drug_names):
        x, y = emb2d[i, 0], emb2d[i, 1]
        xj = x + np.random.uniform(-jx, jx)
        yj = y + np.random.uniform(-jy, jy)
        t = plt.text(
            xj, yj, trunc(drug),
            color='black',
            fontsize=35,
            fontweight='medium',
            alpha=0.9,
            bbox=dict(
                facecolor='white',
                edgecolor=VALIDATION_STYLE["color"],
                alpha=0.9,
                pad=1.5,
                boxstyle='round,pad=0.3'
            )
        )
        existing_texts.append(t)

    plt.title("Validation Drug List UMAP Visualization",
              pad=25, fontsize=42, fontweight='bold', color='#2C3E50')
    plt.xlabel("UMAP Dimension 1", labelpad=15, fontsize=40, color='#2C3E50')
    plt.ylabel("UMAP Dimension 2", labelpad=15, fontsize=40, color='#2C3E50')
    ax.tick_params(axis='both', which='major', labelsize=32)
    plt.grid(True, linestyle='--', alpha=0.3, color='#95A5A6')

    legend_handles = [Patch(facecolor='white',
                            edgecolor=VALIDATION_STYLE["color"],
                            label=VALIDATION_STYLE["name"],
                            alpha=0.9)]
    plt.legend(handles=legend_handles, loc="upper right",
               fontsize=40, frameon=True, facecolor='white',
               edgecolor='none', framealpha=0.9)

    plt.subplots_adjust(left=0.1, right=0.9, top=0.9, bottom=0.1)

    out_path = os.path.join(PLOTS_DIR, "validation_drugs_umap.png")
    plt.savefig(out_path, dpi=600, bbox_inches='tight',
                facecolor='#F8F9F9', edgecolor='none')
    logger.info("UMAP plot saved to %s", out_path)


if __name__ == "__main__":
    main()