# Please note that the plot generated by this script shows the same data as the figure in the paper. However, in the paper the layout was adapted to fit the page
# and to make the labels readable.
# These adjustments were done manually by using the interactive GUI of matplotlib.
# If make use of plt.show(), the plot will be displayed in the interactive GUI of matplotlib and you can perform layout adjustments there
# However, this approach is unsuitable for the pipeline and for the Docker container.

import os
import json
import csv
import requests
import logging
import numpy as np
import umap.umap_ as umap
import matplotlib.pyplot as plt
from matplotlib import rcParams
from typing import Dict, List, Tuple

# ---------- Minimal config (env overrides) ----------
EMBED_URL      = os.getenv("EMBED_URL", "http://ollama:11434/api/embed")
EMBED_MODEL    = os.getenv("EMBED_MODEL", "nomic-embed-text")
TOP100_DIR     = os.getenv("TOP100_DIR", "/app/exports/top_100_drugs_for_umap_plot")
PLOTS_DIR      = os.getenv("PLOTS_DIR", "/app/exports/plots")
LITERATURE_JSON= os.getenv("LITERATURE_JSON", "/app/datasets/cummings_eta_al_AD_DR_candidates.json")

# Expected CSV filenames (produced by step 22)
ZERO_SHOT_CSV  = os.path.join(TOP100_DIR, "zero_shot_top_100.csv")
ONTO_CSV       = os.path.join(TOP100_DIR, "ontological_prompt_top_100.csv")

# ---------- Logging (keep verbose for visibility) ----------
logging.basicConfig(
    format="%(asctime)s [%(levelname)s] %(message)s",
    level=logging.INFO
)
logger = logging.getLogger(__name__)

# ---------- Plot look ----------
plt.style.use('seaborn-v0_8-whitegrid')
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Arial', 'Helvetica', 'DejaVu Sans']

APPROACH_STYLES = {
    "zero_shot":          {"color": "#0072B2", "name": "Zero-Shot Prompting"},
    "ontological_prompt": {"color": "#D55E00", "name": "Ontology-Based Prompting"},
    "literature":         {"color": "#009E73", "name": "Literature Comparison"},
}

# ---------- Embeddings ----------
def get_embedding_for_drug(drug: str, model: str) -> np.ndarray | None:
    payload = {"model": model, "input": drug}
    try:
        resp = requests.post(EMBED_URL, json=payload, timeout=60)
        resp.raise_for_status()
        data = resp.json()
        # Ollama /embed returns {"embeddings":[[...]]}
        emb_list = data.get("embeddings", [[]])[0]
        if not emb_list:
            logger.warning("Empty embedding for '%s'", drug)
            return None
        return np.array(emb_list, dtype=np.float32)
    except Exception as e:
        logger.error("Embedding fetch failed for '%s': %s", drug, e)
        return None

def embed_drug_list(drugs: List[str], model: str) -> Dict[str, np.ndarray]:
    out: Dict[str, np.ndarray] = {}
    for d in drugs:
        emb = get_embedding_for_drug(d, model)
        if emb is not None:
            out[d] = emb
        else:
            logger.warning("Skipping '%s' (no embedding).", d)
    return out

# ---------- IO helpers ----------
def _read_top_list_csv(path: str) -> List[str]:
    """
    Accepts CSVs produced in step 22. They at least contain a 'name' column.
    If the CSV is a single-column (just names), handle that too.
    """
    if not os.path.exists(path):
        logger.error("Top list CSV not found: %s", path)
        return []
    names: List[str] = []
    try:
        with open(path, newline='', encoding="utf-8") as f:
            reader = csv.DictReader(f)
            if reader.fieldnames and 'name' in reader.fieldnames:
                for row in reader:
                    n = (row.get('name') or "").strip()
                    if n:
                        names.append(n)
            else:
                # Try generic CSV read (first column)
                f.seek(0)
                reader2 = csv.reader(f)
                for row in reader2:
                    if row:
                        val = (row[0] or "").strip()
                        if val and val.lower() != "name":
                            names.append(val)
    except Exception as e:
        logger.error("Failed reading CSV %s: %s", path, e)
        return []
    logger.info("Loaded %d drug names from %s", len(names), path)
    return names

def _read_literature_json(path: str) -> List[str]:
    """
    Reads /app/datasets/cummings_eta_al_AD_DR_candidates.json
    Accepts either a list of strings or a dict whose keys are names.
    """
    if not os.path.exists(path):
        logger.error("Literature JSON not found: %s", path)
        return []
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            return [str(x).strip() for x in data if str(x).strip()]
        elif isinstance(data, dict):
            return [str(k).strip() for k in data.keys() if str(k).strip()]
        else:
            logger.error("Unexpected JSON structure in %s; expected list or dict.", path)
            return []
    except Exception as e:
        logger.error("Failed reading literature JSON %s: %s", path, e)
        return []

# ---------- Similarity helpers, not strictly required to plot) ----------
def cosine_similarity(a: np.ndarray, b: np.ndarray) -> float:
    denom = (np.linalg.norm(a) * np.linalg.norm(b))
    if denom == 0:
        return 0.0
    return float(np.dot(a, b) / denom)

# ---------- Combine and visualize ----------
def combine_embeddings_for_visualization(all_embeddings: Dict[str, Dict[str, np.ndarray]]
                                       ) -> Tuple[np.ndarray, List[str], List[str]]:
    vectors: List[np.ndarray] = []
    labels:  List[str] = []
    names:   List[str] = []
    for approach, emb_map in all_embeddings.items():
        for drug, vec in emb_map.items():
            vectors.append(vec)
            labels.append(approach)
            names.append(drug)
    if not vectors:
        return np.zeros((0, 2), dtype=np.float32), labels, names
    return np.vstack(vectors), labels, names

def main() -> int:
    os.makedirs(PLOTS_DIR, exist_ok=True)

    # Build approach -> list-of-names
    approach_lists: Dict[str, List[str]] = {
        "zero_shot":          _read_top_list_csv(ZERO_SHOT_CSV),
        "ontological_prompt": _read_top_list_csv(ONTO_CSV),
        "literature":         _read_literature_json(LITERATURE_JSON),
    }

    # Remove empty approaches (but keep a warning)
    approach_lists = {k: v for k, v in approach_lists.items() if v}
    if not approach_lists:
        logger.critical("No approach lists found. Ensure step 22 CSVs and literature JSON exist.")
        return 1

    # Embed all approaches
    all_embeddings: Dict[str, Dict[str, np.ndarray]] = {}
    for approach, names in approach_lists.items():
        logger.info("Embedding %d drugs for approach '%s' using model '%s'.", len(names), approach, EMBED_MODEL)
        all_embeddings[approach] = embed_drug_list(names, EMBED_MODEL)

    # Combine and reduce with UMAP
    combined_embeddings, labels, _drug_names = combine_embeddings_for_visualization(all_embeddings)
    if combined_embeddings.shape[0] == 0:
        logger.critical("No embeddings to visualize.")
        return 1

    reducer = umap.UMAP(n_components=2, random_state=42)
    logger.info("Fitting UMAP on %d embeddings.", combined_embeddings.shape[0])
    embedding_2d = reducer.fit_transform(combined_embeddings)
    embedding_2d = embedding_2d * 200.0  # spread out points

    # Plot
    fig = plt.figure(figsize=(16, 12))
    ax = plt.gca()
    ax.set_facecolor('#F8F9F9')
    plt.gcf().set_facecolor('#F8F9F9')

    for approach in set(labels):
        idxs = [i for i, lab in enumerate(labels) if lab == approach]
        style = APPROACH_STYLES.get(approach, {"color": "gray", "name": approach})
        plt.scatter(
            embedding_2d[idxs, 0],
            embedding_2d[idxs, 1],
            c=style["color"],
            label=style["name"],
            alpha=0.7,
            edgecolors='k',
            s=100
        )

    plt.title("Prompting Approaches for AD Drug Repurposing compared by Embedding",
              pad=25, fontsize=25, fontweight='bold', color='#2C3E50')
    plt.xlabel("UMAP Dimension 1", labelpad=15, fontsize=25, color='#2C3E50')
    plt.ylabel("UMAP Dimension 2", labelpad=15, fontsize=25, color='#2C3E50')
    ax.tick_params(axis='both', which='major', labelsize=20)
    plt.grid(True, linestyle='--', alpha=0.3, color='#95A5A6')

    plt.legend(loc="best", fontsize=20, frameon=True, facecolor='white', edgecolor='none', framealpha=0.9)
    plt.subplots_adjust(left=0.1, right=0.9, top=0.9, bottom=0.1)

    out_path = os.path.join(PLOTS_DIR, "approaches_umap_plot.png")
    plt.savefig(out_path, dpi=600, bbox_inches='tight', facecolor='#F8F9F9', edgecolor='none')
    logger.info("UMAP plot saved to %s", out_path)

    plt.close(fig)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())